# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-06 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pic',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
