# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-15 06:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.IntegerField(default=0)),
                ('availability', models.BooleanField(default=True)),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.Restaurant')),
            ],
        ),
    ]
