# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-18 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dept', models.CharField(max_length=50)),
                ('eff_date', models.DateField()),
            ],
        ),
    ]
