# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-19 04:21
from __future__ import unicode_literals

import assignment.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_auto_20181218_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eff_date', models.DateField(verbose_name=assignment.models.Employee)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='eff_date',
        ),
        migrations.AddField(
            model_name='details',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.Employee'),
        ),
    ]
