# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-19 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_auto_20181219_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='eff_date',
            field=models.DateField(),
        ),
    ]
