# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-19 06:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0004_auto_20181219_0510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='salary',
        ),
        migrations.AddField(
            model_name='details',
            name='salary',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='salary', to='assignment.Employee'),
        ),
        migrations.AlterField(
            model_name='details',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department', to='assignment.Employee'),
        ),
        migrations.AlterField(
            model_name='details',
            name='eff_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effective_date', to='assignment.Employee'),
        ),
    ]
