# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-19 08:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0006_auto_20181219_0615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='eff_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='salary',
        ),
        migrations.AddField(
            model_name='details',
            name='employee_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='empl_id', to='assignment.Employee'),
        ),
        migrations.AlterField(
            model_name='details',
            name='dept',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='details',
            name='eff_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='details',
            name='salary',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
