language: generic
sudo: required
services: 
  -docker
before_install:
  - docker build -t dineshkumarkb/docker-test -f Dockerfile.dev .
script:
  - docker run -e CI=true dineshkumarkb/docker-test npm run test
deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-test"
  env: "DockerTest-env"
  bucket_name: "elasticbeanstalk-ap-south-1-356557141330"
  bucket_path: "docker-test"
  on:
    branch: master
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_KEY